# Start with the official OpenJDK 17 image as the base
FROM openjdk:17-jdk-slim

# Set the working directory in the container
WORKDIR /app

# Copy the Maven wrapper and pom.xml to the container
COPY .mvn/ .mvn
COPY mvnw pom.xml ./

# Run Maven to download dependencies and build the JAR file
RUN ./mvnw dependency:resolve
RUN ./mvnw package -DskipTests

# Copy the JAR file generated by Maven to the container
COPY target/tradingdashboardnew-0.0.1-SNAPSHOT.jar app.jar

# Expose the port that the application will run on
EXPOSE 10000

# Run the JAR file
CMD ["java", "-jar", "app.jar"]
